name: apiverve_dictionary
description: Dictionary is a simple tool for getting word definitions. It returns the definition a word.
version: 1.1.14
homepage: https://dictionary.apiverve.com?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/dictionary-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
